Update code-2.0.4.1-oscar.log
FIxed

julia> automorphisms(K)
 ERROR: UndefVarError: `automorphisms` not defined in `Main`
 Suggestion: check for spelling errors or missing imports.
 Stacktrace:
  [1] top-level scope
    @ none:1

julia> Qx, x = PolynomialRing(QQ); K, a = NumberField(x^2 + 1);
 ERROR: UndefVarError: `PolynomialRing` not defined in `Main`
 Suggestion: check for spelling errors or missing imports.
 Stacktrace:
  [1] top-level scope
    @ none:1