Update code-1.1.1.1-oscar.log
fixed lines 21 to 27:

julia> automorphisms(K)
 ERROR: UndefVarError: `automorphisms` not defined in `Main`
 Suggestion: check for spelling errors or missing imports.
 Stacktrace:
  [1] top-level scope
    @ none:1